- .gitattributes
- .gitignore
Add `.gitignore` for Python files and `.gitattributes` for LFS.
Katrin Bauer <[katrin.b.bauer@daimler.com](mailto:katrin.b.bauer@daimler.com)>, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
> Add gitignore and gitattributes

- .gitignore
- README.md
- odxtools/cli/_print_utils.py
- odxtools/cli/find.py
- odxtools/cli/list.py
- odxtools/cli/main.py
- odxtools/cli/snoop.py
Adds a find command to the odxtools, allowing you to search &
decode services by hex-byte-data. Also allows searching
by service name.
--
Florian Roks \<florian.roks@daimler.com\>, Daimler TSS GmbH
[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
Licensed under MIT
> Add find command

- odxtools/communicationparameter.py
- odxtools/compumethods.py
- odxtools/diagcodedtypes.py
- odxtools/diaglayer.py
This PR fixes various issues that occured when reading some of our internal diagnostic description files.
Andreas Lauser &lt;<andreas.lauser@daimler.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
> Various small loading robustness improvements

- odxtools/compumethods.py
Removes duplicated function that failed.
--
Florian Roks \<florian.roks@daimler.com\>, Daimler TSS GmbH
[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
> Remove duplicated function

- README.md
- examples/somersaultlazy.py
- odxtools/compumethods.py
- odxtools/decodestate.py
- odxtools/diagcodedtypes.py
- odxtools/encodestate.py
- odxtools/parameters.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
Add some unit tests inspired by #21
Katrin Bauer <[katrin.b.bauer@daimler.com](mailto:katrin.b.bauer@daimler.com)>, on behalf of [MBition GmbH](https://mbition.io/).
> Add tests for decoding

- odxtools/compumethods/linearcompumethod.py
- odxtools/compumethods/readcompumethod.py
referring to ODX spec COMPU-NUMERATOR could be a float.
> support float COMPU-NUMERATOR

- odxtools/version.py
IMO we are long past the beta stage with this project...
> increase the version to 1.0.0

- README.md
- odxtools/version.py
- requirements.txt
- setup.py
Fix a few minor issues regarding pypi packaging just to get a smooth experience.
> fix pypi packaging issues

- odxtools/cli/main.py
Sometimes it is convenient to know which version is used...
> CLI: add a --version flag

- odxtools/structures.py
> structures: make the long name optional

- odxtools/compumethods/readcompumethod.py
- odxtools/compumethods/tabintpcompumethod.py
- odxtools/pdx_stub/macros/printDOP.tpl
- tests/test_compu_methods.py
Fixes [#12](https://github.com/mercedes-benz/odxtools/issues/12)
Katrin Bauer <[katrin.b.bauer@mercedes-benz.com](mailto:katrin.b.bauer@mercedes-benz.com)>, on behalf of [MBition GmbH](https://mbition.io/).
> Add `TAB-INTP` compu method

- odxtools/cli/_print_utils.py
- odxtools/cli/find.py
- odxtools/singleecujob.py
Fixes some issues in the find command (hashability, printing)
---
Florian Roks \<florian.roks@mercedes-benz.com\>, Mercedes-Benz Tech Innovation GmbH
[Provider information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)
> fix issues in find command with SingleEcuJob

- odxtools/compumethods/readcompumethod.py
See https://stackoverflow.com/a/20130067
> Fix detection of missing factor

- odxtools/table.py
Not sure of how you want to handle TABLE-ROW-REF, this PR is a proposal of how to handle them
Note:
* This will convert TABLE-ROW-REF internally to a normal TABLE-ROW, once written back the ODX will contain TABLE-ROW-REF converted to TABLE-ROW
> Support TABLE-ROW-REF

- odxtools/structures.py
- tests/test_encoding.py
Include test case for #70, but not a fix since I still can't get my head around how that function works
> Fix BasicStructure bit_length

- odxtools/compumethods/readcompumethod.py
Same as #65 but for compu scale
Note: a PDX that reproduce the issue could be found in https://github.com/speedbyte/code_composer_build/tree/a34f54cdee679d0b1104b527aafde5f17054634c/doc/Diagnose/PDX
> Support compu scale with int written as float

- odxtools/admindata.py
- odxtools/cli/browse.py
- odxtools/cli/find.py
- odxtools/cli/list.py
- odxtools/cli/main.py
- odxtools/cli/snoop.py
- odxtools/database.py
- odxtools/envdatadesc.py
- odxtools/utils.py
This fixes a bunch of smaller issues which crept in recently.
the morale is that we definitely better unit tests soon...
> Fix various issues

- odxtools/structures.py
@smileprem could you check if this solves #85 ?
> Count padding bits in structure bit length

- odxtools/admindata.py
- odxtools/audience.py
- odxtools/communicationparameter.py
- odxtools/companydata.py
- odxtools/compumethods/readcompumethod.py
- odxtools/dataobjectproperty.py
- odxtools/diagcodedtypes.py
- odxtools/diaglayer.py
- odxtools/endofpdufield.py
- odxtools/envdata.py
- odxtools/envdatadesc.py
- odxtools/functionalclass.py
- odxtools/multiplexer.py
- odxtools/parameters/readparameter.py
- odxtools/service.py
- odxtools/singleecujob.py
- odxtools/state.py
- odxtools/state_transition.py
- odxtools/structures.py
- odxtools/table.py
- odxtools/units.py
> Use findtext where applicable

- odxtools/admindata.py
- odxtools/cli/snoop.py
- odxtools/structures.py
- odxtools/templates/macros/printAdminData.xml.jinja2
Here are some fixes for issues I've found during my constructor refactoring quest (https://github.com/mercedes-benz/odxtools/pull/104 ). While these patches are IMO significant in aggregate, I don't think that each of them merits an individual PR. If you want to review the changes in a coherent way, please have a go at the individual commits...
> Minor fixes

- .github/workflows/tests.yml
- .gitignore
- examples/__init__.py
- examples/mksomersaultpdx.py
- test-requirements.txt
The refactoring introduces a matrix workflow with 2 DOF: OS and Python version. We avoid setting environment variables to make the workflow run on both Windows and Ubuntu in the same manner.
David Holtz <[david.holtz@mbition.io](mailto:david.holtz@mbition.io)>, on behalf of [MBition GmbH](https://mbition.io/).
> Refactor GitHub Action test-and-lint workflow

- odxtools/companydata.py
- odxtools/database.py
- odxtools/nameditemlist.py
- odxtools/service.py
- odxtools/templates/macros/printService.xml.jinja2
This PR contains a few spin-off fixes from #137. These are pretty small and putting them into a separate hopefully #137 a bit more focused...
> Refactor init spinoffs

- odxtools/decodestate.py
- odxtools/diagcodedtypes.py
- odxtools/encodestate.py
- odxtools/endofpdufield.py
- odxtools/multiplexer.py
- odxtools/nameditemlist.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameterbase.py
- odxtools/parameters/parameterwithdop.py
- odxtools/structures.py
- tests/test_diag_coded_types.py
This PR features a bunch of smallish quality-of-life changes which might have minor functional and semantic consequences.
> Smallish improvements

- examples/somersaultecu.py
- odxtools/communicationparameterref.py
- odxtools/compumethods/compumethod.py
- odxtools/createanystructure.py
- odxtools/dataobjectproperty.py
- odxtools/diagcodedtype.py
- odxtools/diaglayercontainer.py
- odxtools/diaglayerraw.py
- odxtools/diagservice.py
- odxtools/endofpdufield.py
- odxtools/environmentdata.py
- odxtools/environmentdatadescription.py
- odxtools/leadinglengthinfotype.py
- odxtools/matchingparameter.py
- odxtools/minmaxlengthtype.py
- odxtools/multiplexer.py
- odxtools/multiplexercase.py
- odxtools/multiplexerdefaultcase.py
- odxtools/multiplexerswitchkey.py
- odxtools/paramlengthinfotype.py
- odxtools/request.py
- odxtools/response.py
- odxtools/standardlengthtype.py
- odxtools/table.py
- odxtools/tablerow.py
- tests/test_ecu_variant_matching.py
the third batch of dataclass conversions. this one converts quite a few classes, but they are all quite simple...
> Moar dataclasses, part 3

- odxtools/cli/find.py
Fix import location of diagservice
Katja Köhler &lt;katja.koehler@mercedes-benz.com&gt;, on behalf of [MBition GmbH](https://mbition.io/).
> fix import location of diagservice

- odxtools/diaglayer.py
- odxtools/dtcdop.py
- odxtools/message.py
- odxtools/structure.py
After this, all classes which correspond to XML tags in the database should finally be dataclasses.
> The final batch of dataclasses conversions

- odxtools/templates/macros/printAudience.xml.jinja2
- odxtools/templates/macros/printCompanyData.xml.jinja2
- odxtools/templates/macros/printComparam.xml.jinja2
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/templates/macros/printDynamicLengthField.xml.jinja2
- odxtools/templates/macros/printElementID.xml.jinja2
- odxtools/templates/macros/printEndOfPdu.xml.jinja2
- odxtools/templates/macros/printEnvData.xml.jinja2
- odxtools/templates/macros/printEnvDataDesc.xml.jinja2
- odxtools/templates/macros/printFunctionalClass.xml.jinja2
- odxtools/templates/macros/printMux.xml.jinja2
- odxtools/templates/macros/printParam.xml.jinja2
- odxtools/templates/macros/printRequest.xml.jinja2
- odxtools/templates/macros/printResponse.xml.jinja2
- odxtools/templates/macros/printService.xml.jinja2
- odxtools/templates/macros/printSpecialData.xml.jinja2
- odxtools/templates/macros/printState.xml.jinja2
- odxtools/templates/macros/printStateChart.xml.jinja2
- odxtools/templates/macros/printStateTransition.xml.jinja2
- odxtools/templates/macros/printStructure.xml.jinja2
- odxtools/templates/macros/printTable.xml.jinja2
- odxtools/templates/macros/printUnitSpec.xml.jinja2
- odxtools/templates/macros/printVariant.xml.jinja2
I recently started to see differences when listing a [pdxcopy'ed](examples/pdxcopy.py) file compared to the original. finding this was fun!
> write dynamic length fields

- odxtools/basicstructure.py
- odxtools/communicationparameterref.py
- odxtools/companydocinfo.py
- odxtools/companyrevisioninfo.py
- odxtools/dataobjectproperty.py
- odxtools/docrevision.py
- odxtools/dtcdop.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/multiplexer.py
- odxtools/odxtypes.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/systemparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/paramlengthinfotype.py
- odxtools/positioneddataobjectproperty.py
- odxtools/singleecujob.py
- odxtools/standardlengthtype.py
The next episode of the type annotation quest. This one should be pretty light on drive-by fixes...
> Add type annotations, part 4

- odxtools/cli/_parser_utils.py
- odxtools/cli/_print_utils.py
- odxtools/cli/browse.py
- odxtools/cli/find.py
- odxtools/cli/list.py
- odxtools/cli/snoop.py
- odxtools/dopbase.py
This time, the command line tools are annotated. It turned out that this was surprisingly difficult...
> Add type annotations, part 6

- odxtools/basicstructure.py
- odxtools/cli/find.py
- odxtools/diaglayer.py
- odxtools/singleecujob.py
- odxtools/uds.py
- tests/test_cli.py
- tests/test_compu_methods.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_ecu_variant_matching.py
- tests/test_encoding.py
- tests/test_odxtools.py
- tests/test_odxtypes.py
- tests/test_readparameters.py
- tests/test_singleecujob.py
- tests/test_somersault.py
- tests/test_unit_spec.py
- tests/test_utils.py
We're almost done: This fixes the unit tests. After this, only the examples are left...
> Add type annotations, part 7

- odxtools/cli/snoop.py
- the full information about the decoding object is not printed anymore in order to avoid flooding the user with enormous amounts of mostly irrelevant and hard to parse information (only the short name of these objects is now printed)
- each parameter of a request or response gets a separate line
- only settable parameters are printed
- indicate whether the response was positive or negative
- if multiple possibilities exist for decoding responses, print all of them
> improve the readability of the `snoop` tool's output

- odxtools/basecomparam.py
- odxtools/database.py
- pyproject.toml
ODX file had `2.0.1` as model version
> Fix ODX 2.0 compatibility

- odxtools/diagcodedtype.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/paramlengthinfotype.py
- odxtools/standardlengthtype.py
This PR refactors the de- and encoding logic of `DiagCodedType`. The aim is to make the code easier understand, speed it up a bit and to fix a few minor correctness issues...
> Refactor `DiagCodedType` coding

- odxtools/basicstructure.py
- odxtools/cli/_print_utils.py
- odxtools/cli/decode.py
- odxtools/cli/find.py
- odxtools/cli/list.py
- odxtools/database.py
- odxtools/diagcodedtype.py
- pyproject.toml
- tests/test_cli.py
PR is spin-off of PR#249
Katja Köhler &lt;katja.koehler@mercedes-benz.com&gt;, on behalf of [MBition GmbH](https://mbition.io/).
> List improvements

- odxtools/complexcomparam.py
- odxtools/database.py
- odxtools/templates/macros/printComparam.xml.jinja2
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/templates/macros/printDiagComm.xml.jinja2
- odxtools/templates/macros/printEcuVariantPattern.xml.jinja2
- odxtools/templates/macros/printEndOfPdu.xml.jinja2
- odxtools/templates/macros/printEnvData.xml.jinja2
- odxtools/templates/macros/printService.xml.jinja2
- odxtools/templates/macros/printSingleEcuJob.xml.jinja2
- odxtools/templates/macros/printVariant.xml.jinja2
This PR fixes a few omissions and minor screwups in the output writing code. With this, the written PDX files hopefully contain a much larger subset of the information (all?) that is contained by database objects.
> Writing fixes

- odxtools/cli/_print_utils.py
- odxtools/cli/browse.py
- odxtools/cli/compare.py
- odxtools/cli/list.py
This PR contains an assortment of smaller fixes, in particular it introduces a "non-strict" mode for `list` and `compare` and cleans up various minor code quality issues in the `compare` tool.
> Janitorial work

- odxtools/templates/macros/printService.xml.jinja2
resolves https://github.com/mercedes-benz/odxtools/issues/258
> Remove Extra ">" in DIAG-SERVICE jinja

- odxtools/basicstructure.py
- odxtools/dataobjectproperty.py
- odxtools/dopbase.py
- odxtools/dtcdop.py
- odxtools/dynamiclengthfield.py
- odxtools/endofpdufield.py
- odxtools/minmaxlengthtype.py
- odxtools/multiplexer.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/dynamicparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/systemparameter.py
- odxtools/parameters/tableentryparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/paramlengthinfotype.py
- odxtools/standardlengthtype.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_somersault.py
This is the third (and probably second to last) part of the decoding code refactoring PR series. This time, the functions of the DOPs and parameters are changed to the common API defined in the previous part.
> Refactor decoding, part 3

- odxtools/dtcdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/valueparameter.py
- tests/test_decoding.py
also, add a unit test to prevent this from regressing in the future.
> fix encoding of DTCs

- odxtools/basicstructure.py
- odxtools/dynamiclengthfield.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/dynamicparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/systemparameter.py
- odxtools/parameters/tableentryparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/parameters/valueparameter.py
- tests/test_encoding.py
- tests/test_somersault.py
The quest continues. This time the parameters are converted to make use of the new and shiny encoding machinery...
> Refactor encoding, part 3 (parameters)

- odxtools/basicstructure.py
- odxtools/dataobjectproperty.py
- odxtools/dopbase.py
- odxtools/dtcdop.py
- odxtools/dynamiclengthfield.py
- odxtools/endofpdufield.py
- odxtools/environmentdatadescription.py
- odxtools/multiplexer.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/parameters/valueparameter.py
- odxtools/staticfield.py
- tests/test_decoding.py
- tests/test_encoding.py
This is the last of the "heavy lifting" PRs concerned with refactoring the encoding code. After this, only one or two cleanup PRs are in the pipeline...
> Refactor encoding, part 4 (data object properties)

- odxtools/compumethods/linearsegment.py
- odxtools/parameters/systemparameter.py
This PR contains fixes for two minor issues I've found when trying to load some files for my more exotic ECUs.
> Fix systemparameter

- odxtools/compumethods/createanycompumethod.py
this fixes the fallback mechanism for unimplemented compu methods and should thus take care of https://github.com/mercedes-benz/odxtools/issues/331
> `create_any_compu_method_from_et`: fix fallback

- odxtools/dtcdop.py
- odxtools/templates/macros/printDOP.xml.jinja2
- tests/test_decoding.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
This turned out to be a bit more involved than anticipated: In contrast to what the term "linked" implies, linked DTC DOPs are not just informative, but an inheritance mechanism for DTCs...
> Implement LINKED-DTC-DOPs

- odxtools/diagvariable.py
- odxtools/templates/macros/printDiagVariable.xml.jinja2
> DiagVariable: internalize remaining functionality

- odxtools/decodestate.py
- odxtools/encodestate.py
This emerged during the discussion for https://github.com/mercedes-benz/odxtools/pull/386: For A_INT32, we now handle BCD  encodings in non-strict mode (but use the absolute of the provided value), for A_UINT32 we now allow signed encodings in non-strict mode but simply pass through the raw number. Also, we now complain if the value that shall be encoded does not fit into the specified bit length.
> improve the fallback code for some undefined encodings in non-strict mode

- odxtools/tablerow.py
Following up on the discussion in https://github.com/mercedes-benz/odxtools/pull/410 regarding the issue found during the unpickling process for the `TableRow` object reconstruction.
The issue identified during the unpickling process for the `TableRow` object reconstruction is related to the usage of the dataclass with `kw_only=True`. This causes the generated `__init__()` method to require keyword arguments, which interferes with the default pickling behavior. Specifically, pickle typically uses the tuple returned by `__reduce__()`.
To resolve this, I implemented a custom `_reconstruct_tablerow` function that bypasses the `__init__()` method by using `cls.__new__(cls)`. This allows us to create an instance without invoking `__init__()`. In the `__reduce__()` method, I return this …
> Fix the TableRow reconstruction during the unpickling

- odxtools/diaglayers/diaglayer.py
- odxtools/diaglayers/ecuvariant.py
- odxtools/diaglayers/hierarchyelement.py
- odxtools/diaglayers/protocol.py
- odxtools/odxlink.py
- odxtools/subcomponentparamconnector.py
This PR contains a few smallish fixes: The biggest one is a fix for https://github.com/mercedes-benz/odxtools/issues/424 , while the other two are the inversion of a spurious `if` condition in a relatively exotic part of the code (`SubComponentParamConnector`), and the improvement of the error message one gets if the result of a reference resolution does not exhibit the expected type.
> Some fixes

- odxtools/templates/macros/printPhysSegment.xml.jinja2
this was the same issue as #437...
Andreas Lauser <[andreas.lauser@mercedes-benz.com](mailto:andreas.lauser@mercedes-benz.com)>, on behalf of [MBition GmbH](https://mbition.io/).
> PHYS-SEGMENT: fix xsi:type attribute output
