- odxtools/compumethods.py
- tests/test_compu_methods.py
Add properties `LinearCompuMethod.physical_lower_limit` and `LinearCompuMethod.physical_upper_limit`.
Katrin Bauer <[katrin.b.bauer@daimler.com](mailto:katrin.b.bauer@daimler.com)>, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
> Add physical limits to compu methods

- odxtools/diaglayer.py
- odxtools/service.py
- odxtools/structures.py
When a positive or negative response used MatchingRequestParameter,
the parameter was ignored, and the resulting calculated prefixes
for the responses were incomplete.
This caused the wrong service to be matched when using find
for a response in these cases (e.g. if a RecordDataIdentifier
was used for a ReadDataByIdentifier-response)
> Bugfixes handling of MatchingRequestParameter in response-prefixes

- examples/somersaultecu.py
- odxtools/cli/browse.py
- odxtools/compumethods.py
- odxtools/dataobjectproperty.py
- odxtools/diagcodedtypes.py
- odxtools/diaglayer.py
- odxtools/odxtypes.py
- odxtools/parameters.py
- odxtools/pdx_stub/macros/printDOP.tpl
- odxtools/pdx_stub/macros/printVariant.tpl
- odxtools/physicaltype.py
- tests/test_compu_methods.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
- tests/test_odxtypes.py
- tests/test_unit_spec.py
This PR does 3 main things (where the first two cause a lot of commit noise):
* Add an enum for data types, i.e., magical strings like `"A_UINT32"` are replaced by `DataType.A_UINT32`
* The enum also offers methods to `cast` values, so the dicts `ODX_TYPE_PARSER` and `ODX_TYPE_TO_PYTHON_TYPE` shouldn't be used anymore
* Add a class `PhysicalType` for `PHYSICAL-TYPE` elements.
Previously the physical type of a DOP was just represented by the string for the data type (e.g. `dop.physical_data_type == "A_UINT32"`). Besides the data type, odxfiles can also specify a display radix or precision in the physical type.
This does make accessing the data type a bit more complex, i.e., the previous
```python
dop.physical_data_type
```
is now
```python
dop.physical_type.base_data_type.value
```
* …
> Add PhysicalType and rework handling of data types

- odxtools/cli/_print_utils.py
- odxtools/cli/find.py
- odxtools/structures.py
Adds a relaxed output formatting option for the find command, to
allow unknown bit-length fields to be rendered as ascii, and
improve the output of decoded messages.
--
Florian Roks \<florian.roks@daimler.com\>, Daimler TSS GmbH
[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
> Add relaxed output formatting option for find command,

- .github/workflows/tests.yml
- odxtools/audience.py
- odxtools/cli/_print_utils.py
- odxtools/cli/browse.py
- odxtools/cli/find.py
- odxtools/cli/list.py
- odxtools/compumethods.py
- odxtools/database.py
- odxtools/dataobjectproperty.py
- odxtools/diagcodedtypes.py
- odxtools/diaglayer.py
- odxtools/encodestate.py
- odxtools/functionalclass.py
- odxtools/nameditemlist.py
- odxtools/odxtypes.py
- odxtools/parameters.py
- odxtools/service.py
- odxtools/structures.py
- odxtools/uds.py
- odxtools/units.py
- odxtools/write_pdx_file.py
This PR attempts to make the static type checker [`mypy`](https://mypy.readthedocs.io/en/stable/introduction.html) happy.
There's some errors that need to be escaped with `# type: ignore`, because I either couldn't rewrite the code in a type-safe manner or didn't understand why `mypy` had a problem to begin with...
You can run `mypy` with
```
$ mypy --ignore-missing-imports odxtools
Success: no issues found in 42 source files
```
Katrin Bauer <[katrin.b.bauer@daimler.com](mailto:katrin.b.bauer@daimler.com)>, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
> Fix static typing

- odxtools/cli/_print_utils.py
- odxtools/cli/find.py
- odxtools/diaglayer.py
- odxtools/service.py
- odxtools/state.py
- odxtools/state_transition.py
Adds display of state-preconditions to the find command
Adds display of state transitions to the find command
Adds enabled audiences to the find command
Makes DiagService hashable, so it can be used in a dict (used to group services by variants)
--
Florian Roks \<florian.roks@daimler.com\>, Daimler TSS GmbH
[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
> Feature: add states output to find

- odxtools/dataobjectproperty.py
- tests/test_decoding.py
Sometimes it happens that the PDX files are not 100% complete and they miss a DTC which the ECU can occasionally send. Bailing out in this case makes dealing with reading such errors quite cumbersome, so let's refrain from this.
The approach taken for these DTCs is to simply provide the trouble code number without any additional context. (An external tool can then be used to it interpret it.)
> Do not raise an exception when encountering an unknown trouble code

- odxtools/utils.py
Current implimentation fails for sample below DESC, since the attribute will cause `raw_string.startswith("<DESC>")` to fail
```
<DESC TI="some_attribute_value">some value <p> other value</p> end</DESC>
```
Solution based on https://stackoverflow.com/a/3446055/1438522
> Better DESC extraction

- odxtools/compumethods/readcompumethod.py
... instead passing `ElementTree` objects. thanks to [at]minkeetan for the catch.
> readcompumethod: do type conversions on strings

- examples/somersaultlazy.py
- odxtools/write_pdx_file.py
- fix a typo in a variable name
- get rid of the deprecation warnings in the `somersaultlazy.py`
example when using python >=3.10
> minor maintenance

- odxtools/compumethods/readcompumethod.py
ODX XSD does not indicate an upper limit for the number of V elements in COMPU-NUMERATOR, but it does indicate that the minimum number of V elements is 1 and not 2
> Support COMPU-NUMERATOR with only one V

- odxtools/database.py
According to the XSD, DIAG-LAYER-CONTAINER is one choice of what the ODX could contain
The ODX could contain FLASH, ECU-CONFIG, VEHICLE-INFO-SPEC...
If an ODX file in the PDX does not have a DIAG-LAYER-CONTAINER the parser will now ignore it instead of failing the whole PDX.
> Don't fail parsing if one ODX file have no DIAG-LAYER-CONTAINER

- CONTRIBUTING.md
This PR fixes the email address to send the CLA to (and also fixes another link).
Refs https://github.com/mercedes-benz/foss/issues/47.
Oliver Kopp &lt;<oliver.kopp@mercedes-benz.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/). [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md).
> Fix email adress and links

- odxtools/diaglayer.py
- odxtools/exceptions.py
* ref_type is never actually used by the code, making an assert is an overkill
* Using warnings module ensure that we still see the error, but we can choose to ignore it or suppress it
* This servers as reference idea for future cases where checks needs to be made but can be tolerated in some edge cases
> Warn instead of assert when for unkown parent ref type

- odxtools/odxtypes.py
It may sound strange, but I got PDX files from a big OEM, where values are integer but written as float, example `15.0` instead of `15`
> Support for int written as float

- odxtools/parameters/parameterbase.py
- odxtools/structures.py
Handle the case were parameters overlap and have gap between them a bit better
Currently the encoding logic do encode them correctly but still bails if it encounter such parameters due to bit_length checking
One simple example is a struct defining a DTC code, it can be treated as a whole number, or have its individual components each treated as a parameter, for convenience, user could define both in the same struct.
> Better overlap and gap handling

- odxtools/structures.py
* BasicStructure.bit_length do not take into consideration EndOfPduField
* BasicStructure.convert_physical_to_internal recalculates bit_length without taking into consideration overlapped parameters and gaps
Centralize the two implementations into one that takes into consideration the special cases of both
> Centralized struct bit length calculation

- odxtools/compumethods/readcompumethod.py
Comparison for bytearray is well defined in Python
```python
a = bytearray.fromhex('aa')
b = bytearray.fromhex('bb')
print(a < b) # True
print(a > b) # False
```
Using `int` breaks the assert in [odxtools\compumethods\texttablecompumethod.py:](https://github.com/mercedes-benz/odxtools/blob/b56eb61b54fbfca4fa38247c8d5e188344a82efc/odxtools/compumethods/texttablecompumethod.py#L27)
> Use bytearray for scale limit

- odxtools/diagcodedtypes.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/structures.py
- tests/test_diag_coded_types.py
Auto calculate the value of LENGTH-KEY when possible, still honer explicit values for the parameter
> Implicit LENGTH-KEY calculation

- odxtools/cli/dummy_sub_parser.py
- odxtools/cli/main.py
This was forgotten in #78, oops.
Thanks to [at]florocks for the catch!
> Add dummy_parser.py

- .github/workflows/tests.yml
This switches running the unit tests to `pytest` and also generates coverage reports on the CI system. Currently, the lcov report is discarded, so only the synopsis printed on the terminal is of any use. The next step is to upload the coverage results to some sites like codecov.io or coveralls.io to allow for easy inspection and comparison with previous results.
> unit test workflows: switch to pytest and produce simplistic coverage reports

- examples/somersaultecu.py
- odxtools/cli/_parser_utils.py
- odxtools/database.py
- odxtools/diaglayer.py
- odxtools/load_file.py
- odxtools/load_odx_d_file.py
- odxtools/load_pdx_file.py
- tests/test_odxtools.py
- tests/test_somersault.py
The reason for these were that CANdela uses different communication parameter specifications than the ones specified by the `odx-cs` files that are shipped with the ODX standard. This resulted in a different ordering for some of the complex communication parameters (albeit with all required fields being present). Fortunately, with #92 merged, this became unnecessary.
> remove the "CANdela workaround" hacks

- odxtools/exceptions.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/structures.py
- pyproject.toml
During ECU development some constants gets added to list of coded_values or a previously reserved byte gets assigned a meaning or a struct gets added a new parameter in a backward compatible way.
Those kind of decoding errors could be tolerated if needed.
This PR change those errors to warnings, but still do raise them by default as errors through `warnings.simplefilter('error', DecodeError)`
> Allow ignoring non-critical decoding errors

- odxtools/companydata.py
- odxtools/comparam_subset.py
- odxtools/pdx_stub/diag_layer_container.odx-d.tpl
This internalizes the `COMPANY-DATAS` and `ADMIN-DATA` tags for comparam subsets. Besides this, the `allow_multiple_values` can now be `None` to be able to determine if the XML attribute was set in the input file.
> internalize admin data for comparam subsets

- odxtools/database.py
- odxtools/diaglayer.py
When querying communication parameters, this change allows to limit oneself to the protocol one is interested in. Besides that, a convenience property returning a set with the names of all protocols known to the database (`Database.protocol_names`)  is added. 
> Comparams: Implement support for protocols

- README.md
This PR removes the keyword argument `enable_candela_workarounds` from the example in the README, since the keyword argument is no longer supported by odxtools.
David Holtz &lt;<david.holtz@mbition.io>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
> Remove misleading kwarg in example section

- odxtools/diaglayer.py
This is a small feature PR, which adds a method to query the Comparam for the DoIP logical ecu address.
```python
get_doip_logical_ecu_address(self, ...):
```
This comparam is crucial for establishing a DoIP connection with the vehicle. The desired data item is nested in a complex Comparam called `UniqueRespIdTable`.
David Holtz <[david.holtz@mbition.io](mailto:david.holtz@mbition.io)>, on behalf of [MBition GmbH](https://mbition.io/).
> Add method to query the CP_DoIPLogicalEcuAddress

- odxtools/cli/list.py
- odxtools/cli/snoop.py
- odxtools/database.py
- odxtools/diaglayer.py
- setup.py
Seems like the comparams are becoming a never-ending story. They got broken by a2c8e0ea: The problem with the simplified approach is that comparameters with the same name that are specified by low-priority parents are not properly overwritten by the higher-priority ones. This could be fixed by simply always taking the last instead of the first of the filtered comparams, but this approach would IMO not very explicit and it would also not get rid of the "multiple definition of comparam Foo" warnings. So let's revert back to building a dictionary as before a2c8e0ea, but we (a) now use a `(comparam.short_name, protocol_short_name)` tuple as the key and (b) treat the dictionary as an internal implementation detail of the function (i.e., we return a plain list).
Besides this, the protocol …
> Comparam fixes

- examples/somersaultecu.py
- odxtools/admindata.py
- odxtools/audience.py
- odxtools/communicationparameter.py
- odxtools/companydata.py
- odxtools/comparam_subset.py
- odxtools/compumethods/limit.py
- odxtools/compumethods/readcompumethod.py
- odxtools/database.py
- odxtools/dataobjectproperty.py
- odxtools/diagdatadictionaryspec.py
- odxtools/diaglayer.py
- odxtools/endofpdufield.py
- odxtools/envdata.py
- odxtools/envdatadesc.py
- odxtools/functionalclass.py
- odxtools/multiplexer.py
- odxtools/parameters/parameterbase.py
- odxtools/physicaltype.py
- odxtools/service.py
- odxtools/singleecujob.py
- odxtools/specialdata.py
- odxtools/state.py
- odxtools/state_transition.py
- odxtools/structures.py
- odxtools/table.py
- odxtools/units.py
- tests/test_compu_methods.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
This PR is pretty large but quite boring (that's the best combination, isn't it?). These constructors mostly replace the `read_<foo>_from_odx()` functions and follow the convention `<Foo>.from_et(et_elem, doc_frags)`. The new approach has the advantages that much more of the code related to a given class is contained within the class' body and that only the class name (`Foo`) needs to be imported by the consumers.
Not all `read_<foo>_from_odx()` match well to be replaced by this pattern, though:
- Factory functions which create an object of a derived class but return it as an instance of the base class. These have been renamed to `create_any_<foo>_from_et()`, e.g., `create_any_data_object_property_from_et()`.
- Functions which do not return an object of a special-purpose class but e.g. a …
> use named constructors for constructing objects from XML where it makes sense

- odxtools/admindata.py
- odxtools/audience.py
- odxtools/communicationparameter.py
- odxtools/companydata.py
- odxtools/comparam_subset.py
- odxtools/compumethods/__init__.py
- odxtools/compumethods/createanycompumethod.py
- odxtools/dataobjectproperty.py
- odxtools/diagcodedtypes.py
- odxtools/diagdatadictionaryspec.py
- odxtools/diaglayer.py
- odxtools/endofpdufield.py
- odxtools/envdata.py
- odxtools/functionalclass.py
- odxtools/parameters/__init__.py
- odxtools/parameters/createanyparameter.py
- odxtools/service.py
- odxtools/singleecujob.py
- odxtools/specialdata.py
- odxtools/state.py
- odxtools/structures.py
- odxtools/table.py
- odxtools/units.py
- odxtools/utils.py
- tests/test_compu_methods.py
- tests/test_readparameters.py
most of these are factory functions that are now called `create_any_<foo>_from_et()`, while functions which produce a list of objects are called   `create_<foo>s_from_et()`. Finally, unspecific helper functions are called `create_<foo>_from_et()`  (e.g. `create_description_from_et()`)
> rename the remaining `read_<foo>_from_odx()` functions

- examples/somersaultecu.py
- odxtools/audience.py
- odxtools/comparam_subset.py
- odxtools/dataobjectproperty.py
- odxtools/diagcodedtypes.py
- odxtools/endofpdufield.py
- odxtools/odxtypes.py
- odxtools/parameters/createanyparameter.py
- odxtools/parameters/valueparameter.py
- odxtools/singleecujob.py
- odxtools/structures.py
- odxtools/templates/macros/printAudience.xml.jinja2
- odxtools/templates/macros/printComparam.xml.jinja2
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/templates/macros/printSingleEcuJob.xml.jinja2
- odxtools/templates/macros/printSpecialData.xml.jinja2
- odxtools/templates/macros/printTable.xml.jinja2
- odxtools/templates/macros/printUnitSpec.xml.jinja2
- odxtools/utils.py
- odxtools/write_pdx_file.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_singleecujob.py
In ODX, a true value can be specified by either the strings "true" or "1", and a false one by the strings "false" or "0". Also, leading and trailing white space is to be ignored. All of these complications are now dealt with by the new and shiny `str_to_bool()` function. (Suggestions for a better name are appreciated!)
Further, if an attribute of the XML is optional but specified to default to true, `None` must be interpreted as true, which is done by assigning the raw value to a protected attribute `._<foo>` while also defining a property `foo` that returns a boolean...
> fix handling of boolean attributes

- odxtools/parameters/dynamicparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/systemparameter.py
- odxtools/parameters/tableentryparameter.py
In createanyparameter.py the LengthKeyParameter, SystemParameter, DynamicParameter and TableEntryParameter can't be initialised because of a missing keyword argument (sdgs). This can be fixed by adding the kwargs argument.
> Add missing kwargs to several parameter classes

- odxtools/structures.py
The byte_size argument wasn't passed to the parent class.
> Structure: Pass byte_size argument to parent class

- examples/somersaultecu.py
- odxtools/dataobjectproperty.py
- odxtools/odxlink.py
- odxtools/parameters/parameterbase.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/structures.py
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/templates/macros/printEnvData.xml.jinja2
- odxtools/templates/macros/printMux.xml.jinja2
- odxtools/templates/macros/printTable.xml.jinja2
- tests/test_decoding.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
This PR contains a few bug fixes (the files produced using odxtools should now conform to the XSD), cleanups (e.g., DOP handling of `DtcDop`) and small improvements (most notably, it is now possible to specify the expected type of the resolved object for ODXLINK resolution.
> Improvements

- .github/workflows/tests.yml
The goal of this refactoring is to make the CI pipeline more transparent and enhance the traceability of failures.
The new pipeline has
- a lint job (using yapf, see also #119 and #120), 
- a static-type-checking job and
- a test job.
Each job runs independently from each other. To improve efficiency, pip dependencies are cached.
David Holtz <[david.holtz@mbition.io](mailto:david.holtz@mbition.io)>, on behalf of [MBition GmbH](https://mbition.io/).
> Decompose action into CI pipeline jobs

- odxtools/structures.py
- odxtools/templates/comparam-subset.odx-cs.xml.jinja2
- odxtools/templates/macros/printMux.xml.jinja2
- odxtools/templates/macros/printParentRef.xml.jinja2
- odxtools/templates/macros/printService.xml.jinja2
- odxtools/templates/macros/printStructure.xml.jinja2
this contains a few minor fixes for the writing code which prevented `odxtools list` from being "round-trip invariant" on one of our internal files. (i.e. `cantools list` now produces the same output for the original file and for one which was passed through the `pdxcopy` example)
> Various small writing fixes

- examples/somersaultecu.py
- odxtools/communicationparameter.py
- odxtools/database.py
- odxtools/diaglayer.py
- odxtools/diaglayercontainer.py
- odxtools/diaglayertype.py
- odxtools/ecu_variant_matcher.py
- odxtools/parentref.py
- odxtools/templates/macros/printComparamRef.xml.jinja2
- odxtools/write_pdx_file.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_ecu_variant_matching.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
This PR marks the start a small quest of mine to untangle the code spaghetti that is currently located in `diaglayer.py`. This PR moves the `ParentRef` and `DiagLayerContainer` classes into their separate files, renames the `DIAG_LAYER_TYPE` enum to `DiagLayerType` and fixes a small copy-and-pasto in the writing code for communication parameters.
Since all patches are self-contained and simple but some are fairly big, I recommend reviewing this PR by looking at the individual commits instead of the aggregate changes of the whole PR.
> Untangle Diaglayer (1 of X)

- odxtools/comparam_subset.py
- odxtools/diaglayer.py
- odxtools/parentref.py
This continues the long quest to clean up `DiagLayer`:
it turns out that the names of the communication parameters are not unambiguous: e.g., "CP_UniqueRespIdTable" parameter is not so unique in the sense that it exists for CAN (comparam subset "ISO_15765_2") as well as for DoIP (CP subset "ISO_13400_2_DIS_2015") and both parameters have a completely different definition. (The same issue applies to e.g., "CP_TesterPresentTime", but this being a simple integer parameter, at least the returned value is of the same type.)
To get out of that pickle, the full parameter ID now has to be specified for `DiagLayer.get_communication_parameter()` (e.g., "ISO_15765_2.CP_UniqueRespIdTable"). …
> diaglayer: refactor the communication parameter handling

- odxtools/diaglayer.py
this PR just moves related functions of the `DiagLayer` closer together and adds a few comments what the purpose of these functions is. No functional changes are included (hopefully)...
> DiagLayer: group the methods more logically

- odxtools/cli/list.py
- odxtools/diagdatadictionaryspec.py
- odxtools/diaglayer.py
- odxtools/diaglayercontainer.py
- odxtools/endofpdufield.py
- odxtools/parameters/parameterwithdop.py
This PR collects various smaller fixes for the diaglayer code (in that sense, it consists purely of "drive-by" fixes). The most notable of those changes is that the "logical" view now exposes all objects that are contained by the DIAG-DATA-DICTIONARY-SPEC tag using a separate `.data_dictionary_spec` attribute instead of providing e.g. the `.data_object_properties` directly. (This is not completely trivial because some of the sub-objects of the diag data dictionary spec are subject to value inheritance).
> Untangle diaglayer (Part 6)

- odxtools/diaglayer.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parentref.py
- odxtools/structures.py
- tests/test_somersault.py
This is the final PR in the long quest to refactor `DiagLayer`: An overhaul of the code that implements value inheritance. Now, all objects that the spec says shall be subject to the value inheritance mechanism should be covered (modulo bugs), and the mechanism is IMO implemented in a more straight forward way (i.e., with less code duplication as well as all value-inheritance related code being kept in the `DiagLayer` class).
> DiagLayer: refactor the value inheritance mechanism

- odxtools/compumethods/createanycompumethod.py
- odxtools/templates/macros/printDOP.xml.jinja2
- tests/test_compu_methods.py
this is based on @JoSglch's https://github.com/mercedes-benz/odxtools/pull/130, i.e. all praise for this belongs to @JoSglch, while all remaining bugs are my own fault: the differences to the original are that this is rebased on top of the latest version of the `main` branch, some spurious `| int` filters are removed in the writing code, and a small typo in new the unit test has been fixed.
> Fix linear compumethod

- examples/somersaultecu.py
this moves the definition of the tables, multiplexer, environment data and environment data descriptions behind the definition of the global negative responses. This is required because in a later commit, we would like to let the `structure_ref` of the table objects to actual structures, which is greatly simplified if the structures are already defined before the tables.
This commit does not change anything functional in these objects, but since git does not recognize that the code simply moved en-bloc, it makes it very hard to review this if there were any functional changes mixed in.
> somersault ECU: reorder the definition of the data

- odxtools/cli/list.py
the command line argument is called "global-negative-responses", not "global-neg-responses".
fixes #153 
> list: fix typo/thinko

- odxtools/endofpdufield.py
When load pdx file it says some structure is missing. Here may be a typo to assign dop to structure.
> Fix the bug #152

- odxtools/diaglayerraw.py
for whatever reason, an 'S' recently went missing in action...
> fix loading of ECU variant patterns

- examples/somersaultlazy.py
this code has suffered from mild bitrot, and this commit thus changes the following things:
- no deprecated functions are used anymore (e.g. `get_receive_id()` -> `get_can_receive_id()`)
- take advantage of `NamedItemList`'s capability to access items by short name as attributes instead of resolving them manually.
- Use the appropriate helper functions of `DiagLayer` to receive communication parameters instead of doing this manually.
> clean up the example implementation of the lazy somersault ECU

- examples/somersaultecu.py
- odxtools/compumethods/compuscale.py
- odxtools/compumethods/limit.py
- odxtools/dataobjectproperty.py
- odxtools/decodestate.py
- odxtools/diagcodedtypes.py
- odxtools/diagdatadictionaryspec.py
- odxtools/diaglayer.py
- odxtools/ecu_variant_matcher.py
- odxtools/encodestate.py
- odxtools/endofpdufield.py
- odxtools/message.py
- odxtools/multiplexer.py
- odxtools/odxlink.py
- odxtools/odxtypes.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/parameterbase.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/service.py
- odxtools/singleecujob.py
- odxtools/structures.py
- odxtools/uds.py
- tests/test_ecu_variant_matching.py
This PR contains a scattershot of smaller cleanups which improve the esthetics and convenience of the code, but should change nothing to little functionality-wise.
Be aware that it is probably easier to review the patches here individually because they are all focused on a single issue instead of colluding everything together...
> Some random cleanups

- examples/somersaultecu.py
- odxtools/diaglayer.py
- odxtools/encodestate.py
- odxtools/endofpdufield.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/table.py
- odxtools/tablerow.py
- odxtools/templates/macros/printTable.xml.jinja2
- tests/test_diag_data_dictionary_spec.py
this PR refactors the table classes once more:
- Table rows now get a reference to the table which contains them. This is required to resolve SNREFs in table rows.
- In Tables, the table rows are now specified as a mixed list of ODXLINK references and table row objects. The approach is identical to the one for diagnostic communication objects for diagnostic layer. The reason for this is that the XML specification defines rows this way (as with the diagnostic services, `table.table_rows` provides a fully resolved view, while `table.table_rows_raw` is the table row specification as it is found in the XML)
-  The `TableRow` class is put to a separate file and `TableBase` is subsumed into its only user, `Table`.
- The `DiagLayer` class does not hold the table objects directly anymore. …
> Refactor table classes

- examples/somersaultecu.py
- odxtools/singleecujob.py
- odxtools/templates/macros/printSingleEcuJob.xml.jinja2
- odxtools/templates/macros/printUnitSpec.xml.jinja2
- odxtools/unitgroup.py
Since the values of these objects are read from the XML (i.e., at runtime), using `typing.Literal` for them does not work very well: While loading a dataset it is currently not verified that the specified values are valid, and mypy must be instructed to ignore converting the dynamic string to the literal strings. Using `Enum` classes fixes these issues...
> Convert Literal string to Enum classes

- setup.py
In the odxtools stone age, python-can 4.0 causes some exceptions to be raised. This has long been fixed.
This fixes #174.
> Allow to use contemporary versions of python can

- MANIFEST.in
for whatever reason, the `setuptools` heuristic for automatically determining which files ought to be distributed broke down recently, so that all sub-directories of `odxtools/` were no longer part of the pypi package. Explicitly instructing `setuptools` what to include fixes that...
> add a MANIFEST.in

- examples/somersaultecu.py
- odxtools/compumethods/compumethod.py
- odxtools/compumethods/compurationalcoeffs.py
- odxtools/compumethods/compuscale.py
- odxtools/compumethods/createanycompumethod.py
- odxtools/compumethods/identicalcompumethod.py
- odxtools/compumethods/limit.py
- odxtools/compumethods/linearcompumethod.py
- odxtools/compumethods/scalelinearcompumethod.py
- odxtools/compumethods/tabintpcompumethod.py
- odxtools/compumethods/texttablecompumethod.py
- odxtools/parameterinfo.py
- tests/test_compu_methods.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_encoding.py
- tests/test_singleecujob.py
The next part of the quest for the database containing mostly dataclasses. This PR also contains a few drive-by fixes, in particular that we now have a proper class for COMPU-RATIONAL-COEFFS, the CompuScale and Limit classes no longer uses default values, and that CompuScale has a `.from_et()` method.
> Make the compumethods dataclasses

- examples/somersaultecu.py
- odxtools/compumethods/texttablecompumethod.py
- odxtools/progcode.py
- odxtools/templates/macros/printSingleEcuJob.xml.jinja2
- tests/test_singleecujob.py
Instead, make this a string because the SYNTAX subtag of SINGLE-ECU-JOB is specified to be a plain string in the ODX specification. It seems like we wanted to be more strict on our own files and tried to constrain the possible values for this. This was implemented using a string literal (which is like a type-checking only enum, i.e., it does not check if the value specified is valid if can only be determined at runtime). After changing this to an `Enum` class in #172, it got some (incorrect) teeth which bit users that used non-Java single ECU jobs.
> remove the `ProgCodeSyntax` enum class

- odxtools/nameditemlist.py
- tests/test_odxtools.py
OEM files are using short names that start with digit
The generates hundreds of errors/warnings for something that is not against ODX standard
The standard allows for short names to start with digits, so making an assert for it don't make much sense
Users who need to access an item that is a keyword or start with digit will get a syntax error anyway and their code won't run, so the extra assert is pointless.
> Don't assert about short names starting with digits

- odxtools/basicstructure.py
- odxtools/cli/browse.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/dynamicparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/systemparameter.py
- odxtools/parameters/tableentryparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/parameters/valueparameter.py
- tests/test_somersault.py
`Parameter.is_optional()` and `Parameter.is_required()` were quite confusing as it can be assumed that one is just the negation of the other. We thus rename `.is_optional` to `.is_settable` to more clearly express that this indicates that a parameter is user-definable. (In the process, a few instances in the `browse` tool where this seems to have been mixed up are fixed.) While at it, make these functions properties so that they do not need to be called anymore...
> rework .is_required and .is_optional methods of parameters

- examples/isotp_send.py
- odxtools/cli/browse.py
- odxtools/cli/dummy_sub_parser.py
- odxtools/cli/main.py
- odxtools/compumethods/compuscale.py
- odxtools/compumethods/createanycompumethod.py
- odxtools/compumethods/identicalcompumethod.py
- odxtools/compumethods/limit.py
- odxtools/compumethods/linearcompumethod.py
- odxtools/compumethods/scalelinearcompumethod.py
- odxtools/compumethods/tabintpcompumethod.py
- odxtools/isotp_state_machine.py
- odxtools/matchingparameter.py
- odxtools/odxlink.py
- odxtools/progcode.py
- tests/test_cli.py
This is the kick-off PR of another long and winding quest; this time the goal is to add comprehensive type annotations to everything so that `mypy --disallow-untyped-defs` passes for odxtools without any complaints. Note that this quest will include many side-tasks; I indent to put them into separate PRs as much as possible, but it is about as certain as death and taxes that I'll occasionally miss a few of these "drive-by fixes"...
> Add type annotations, part 1

- examples/somersaultecu.py
- odxtools/multiplexercase.py
- odxtools/multiplexerdefaultcase.py
- odxtools/templates/macros/printMux.xml.jinja2
- tests/test_diag_data_dictionary_spec.py
it turns out that these references are (a) optional and (b) can be done via SNREF...
> multiplexer cases: fix internalization of the structure references

- .github/workflows/tests.yml
- odxtools/basicstructure.py
- odxtools/cli/find.py
- odxtools/comparamsubset.py
- odxtools/diagdatadictionaryspec.py
- odxtools/diaglayer.py
- odxtools/diaglayercontainer.py
- odxtools/diaglayerraw.py
- odxtools/diagservice.py
- odxtools/field.py
- odxtools/message.py
- odxtools/nameditemlist.py
- odxtools/odxtypes.py
- odxtools/response.py
- odxtools/singleecujob.py
- pyproject.toml
- tests/test_decoding.py
- tests/test_somersault.py
This PR consists of fixes for issues I've noticed while preparing [#203](https://github.com/mercedes-benz/odxtools/pull/203). It turned out to be quite a bit larger than the motivating PR...
(note: all patches of this PR are fully self-contained and the PR is also bisectable. Since all commits should be basically independent of each other, it is probably easier to review the PR by looking at the patches individually instead of the cumulative diff.)
> Drive by fixes #1

- odxtools/basicstructure.py
- odxtools/dataobjectproperty.py
- odxtools/decodestate.py
- odxtools/diagcodedtype.py
- odxtools/dtcdop.py
- odxtools/endofpdufield.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/multiplexer.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/paramlengthinfotype.py
- odxtools/positioneddataobjectproperty.py
- odxtools/standardlengthtype.py
- tests/test_diag_coded_types.py
IMO, `.cursor_position` better captures the purpose of this attribute.
this is a spin-off of #210 proposed by @kayoub5.
> rename `DecodeState.next_byte_position` to `DecodeState.cursor_position`

- odxtools/minmaxlengthtype.py
This PR is one of the first baby steps towards untangling the de-/encoding functionality. It renames `DecodeState.next_byte_position` to `DecodeState.cursor_position`, and cleans up the de- and encoding code of the `MinMaxLengthType` DOP.
> Refactor `MinMaxLengthType` coding functionality

- README.md
- odxtools/compumethods/compumethod.py
- odxtools/compumethods/createanycompumethod.py
- odxtools/compumethods/identicalcompumethod.py
- odxtools/compumethods/limit.py
- odxtools/compumethods/linearcompumethod.py
- odxtools/compumethods/scalelinearcompumethod.py
- odxtools/compumethods/tabintpcompumethod.py
- odxtools/compumethods/texttablecompumethod.py
- odxtools/dataobjectproperty.py
- odxtools/diagcodedtype.py
- odxtools/isotp_state_machine.py
- odxtools/modification.py
- odxtools/parameterinfo.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/dynamicparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/systemparameter.py
- odxtools/parameters/tableentryparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/parameters/valueparameter.py
- odxtools/physicaldimension.py
- odxtools/physicaltype.py
- odxtools/unit.py
This is the second part of the quest for comprehensive type annotations. Besides the on-topic changes, it also contains a minor cleanup of the README, and the removal of the completely unused but confusingly named `Parameter.get_coded_value()` method.
> Add type annotations, part 2

- odxtools/basicstructure.py
- odxtools/cli/browse.py
- odxtools/compumethods/tabintpcompumethod.py
- odxtools/compumethods/texttablecompumethod.py
- odxtools/dataobjectproperty.py
- odxtools/diaglayer.py
- odxtools/diagnostictroublecode.py
- odxtools/diagservice.py
- odxtools/dopbase.py
- odxtools/dynamiclengthfield.py
- odxtools/endofpdufield.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/dynamicparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/tableentryparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/parameters/valueparameter.py
- odxtools/unitgroup.py
- odxtools/unitspec.py
This is the third part of the quest for comprehensive type annotations. It is mainly concerned about the parameter classes, but as usual, it also contains a few drive-by fixes, namely the removal of the confusingly named and functionally unused method `DataObjectProperty.get_valid_physical_values()` and the removal of the unused `.as_dict()` methods of various classes.
> Add type annotations, part 3

- odxtools/cli/_parser_utils.py
- odxtools/cli/snoop.py
- odxtools/isotp_state_machine.py
Make it work without a PDX-file
Christian Hackenbeck &lt;christian.hackenbeck@mercedes-benz.com&gt;, on behalf of [MBition GmbH](https://mbition.io/).
> iso statemachine make it work for CAN FD

- examples/somersaultecu.py
- examples/somersaultlazy.py
this makes `mypy --disallow-untyped-defs` happy with the examples and thus concludes the main part of the type annotation saga: There will be another small PR coming which enables the `--disallow-untyped-defs` mypy option in `pyproject.toml`, but that one is tiny (besides the philosophical implications).
Besides the type annotations, this patch may also contains a small number of drive-fixes for minor issues I've encountered along the way. Sorry for that in advance...
> Add type annotations, part 8

- odxtools/message.py
- pyproject.toml
This PR enables the `--disallow-untyped-defs` mypy option by default, and adds back the `Message.structure` attribute as a deprecated alias for `Message.coding_object` (this should significantly reduce the pain of upgrading from an older version).
> Get ready for release

- odxtools/nameditemlist.py
it turns out that an *explicit* list with all possibilities is required for the REPL tab completion code to show the list of all possibilities (duh!). (The `__getattr__()` method is obviously implicit, but we still need it to keep mypy happy...)
note that this change doesn't have an effect on scripts because tab completion is a purely interactive thing.
> NamedItemList: make tab completion for NamedItemList work again

- odxtools/utils.py
instead, use `inspect.signature()`. This should slightly reduce the long-term maintainance burden because even if the internals of dataclasses change over time, `inspect.signature()` should continue to work...
> `dataclass_fields_asdict()`: do not use internals of the dataclass implementation

- README.md
- odxtools/cli/decode.py
- odxtools/cli/find.py
- odxtools/cli/main.py
- tests/test_cli.py
Fix issue with find command requiring data, by splitting the decode and find (by service name) functionalities
into separate commands.
> Split find into find and decode

- odxtools/basicstructure.py
Fix an issue, in which overlapping parameters were shown separately
Overlapping parameters happen when you define parameters with different bit-lengths at the same byte-position.
Example:
Define parameter X at position 3 with bit-length 24
Define parameter Y at position 3 with bit-length 8
Define parameter Z at position 4 with bit-length 8
Define parameter A at position 5 with bit-length 8
> Fix an issue, in which overlapping parameters were shown separately

- odxtools/diaglayer.py
- odxtools/leadinglengthinfotype.py
- odxtools/obd.py
- odxtools/parameters/codedconstparameter.py
- odxtools/servicebinner.py
- odxtools/uds.py
- odxtools/udsbinner.py
- tests/test_odxtools.py
This is a convenience functionality to quickly find the diagnostic services one is interested in for ECUs offering lots of services. The simplest way to use it is using the `.print_info()` method:
```python
ecu.uds_service_groups.print_info()
```
That said, bins can also be programmatically processed:
```python
session_services = ecu.uds_service_groups[0x10]
print("The services concerning diagnostic sessions are:")
for session in session_services:
print(f"  {service.short_name}")
```
> diag_layer: allow to access services according to their UDS service group (SID)

- .github/workflows/tests.yml
Python 3.12 has been released about a month ago. It would be nicer to increase the minimum required version to 3.10, but that has to wait at least until Ubuntu 20.04 falls out of support...
> workflows: update the "bleeding edge" python version to 3.12

- odxtools/diagdatadictionaryspec.py
- odxtools/parameters/parameterwithdop.py
- odxtools/tablerow.py
- tests/test_diag_data_dictionary_spec.py
it turned out that this is useful. this time, we add a unit test and also use it internally to resolve DOP-SNREFs for places where complex DOPs can be referenced via SNREF (i.e., some of the parameters).
> DiagDataDictionarySpec: re-introduce the all_data_object_properties attribute

- odxtools/basicstructure.py
- odxtools/complexdop.py
- odxtools/environmentdatadescription.py
- odxtools/field.py
- odxtools/multiplexer.py
This class does not do anything, but the ODX specification does it this way and it can be used to distinguish simple from complex DOPs more elegantly at runtime...
> Introduce `ComplexDop` as a base class for non-simple data object properties

- odxtools/complexcomparam.py
Addresses https://github.com/mercedes-benz/odxtools/issues/236
> fix ComplexComparam `from_et` function

- odxtools/templates/macros/printAudience.xml.jinja2
- odxtools/templates/macros/printCompanyData.xml.jinja2
- odxtools/templates/macros/printComparam.xml.jinja2
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/templates/macros/printDiagComm.xml.jinja2
- odxtools/templates/macros/printDynamicLengthField.xml.jinja2
- odxtools/templates/macros/printElementId.xml.jinja2
- odxtools/templates/macros/printEndOfPdu.xml.jinja2
- odxtools/templates/macros/printEnvData.xml.jinja2
- odxtools/templates/macros/printEnvDataDesc.xml.jinja2
- odxtools/templates/macros/printFunctionalClass.xml.jinja2
- odxtools/templates/macros/printMux.xml.jinja2
- odxtools/templates/macros/printParam.xml.jinja2
- odxtools/templates/macros/printRequest.xml.jinja2
- odxtools/templates/macros/printResponse.xml.jinja2
- odxtools/templates/macros/printSingleEcuJob.xml.jinja2
- odxtools/templates/macros/printSpecialData.xml.jinja2
- odxtools/templates/macros/printState.xml.jinja2
- odxtools/templates/macros/printStateChart.xml.jinja2
- odxtools/templates/macros/printStateTransition.xml.jinja2
- odxtools/templates/macros/printStructure.xml.jinja2
- odxtools/templates/macros/printTable.xml.jinja2
- odxtools/templates/macros/printUnitSpec.xml.jinja2
- odxtools/templates/macros/printVariant.xml.jinja2
The jinja macro for writing the SHORT-NAME, LONG-NAME and DESC tags is now called `printElementIdSubtags` to avoid giving the impression that it writes a full `ELEMENT-ID` tag instead of just its contents.
Unless a better scheme comes along, this will also be the new way to deal with inherited classes when writing XML files: If Bar derives from Foo, there will be `printFooSubtags` and `printFooAttributes` macros, which are then called by `printBar`. The first two macros do not write the complete tag, but only the contents and the attributes defined by Foo.
> slightly improve writing the sub-tags stemming from ELEMENT-ID

- odxtools/database.py
- odxtools/diaglayer.py
- odxtools/diaglayerraw.py
- odxtools/protstack.py
- odxtools/templates/comparam-spec.odx-c.xml.jinja2
- odxtools/templates/macros/printProtStack.xml.jinja2
- odxtools/write_pdx_file.py
It turns out that files containing "COMPARAM-SPEC" root elements were ignored for PDX files using ODX 2.2. (also, the writing code got slightly broken recently.)
I'm not 100% sure if this still works with ODX 2.0 files, though...
> fix parsing and writing of COMPARAM-SPEC

- examples/somersaultecu.py
- odxtools/dataobjectproperty.py
- odxtools/internalconstr.py
- odxtools/scaleconstr.py
- odxtools/templates/macros/printDOP.xml.jinja2
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
Implemented the classes based on the schema in ISO 22901-1:2008 pg. 376-377, 394
> Add support for InternalConstr

- odxtools/dataobjectproperty.py
The value range of <PHYS-CONSTR> should be defined by the <physical_type> field.
> physical_type bug fix

- examples/somersaultecu.py
- odxtools/basicstructure.py
- odxtools/comparamsubset.py
- odxtools/database.py
- odxtools/nameditemlist.py
- tests/test_odxtools.py
With this applied, whenever a `List` is expected by the type checker, a `NamedItemList` object can be used as well.
Besides this, I cleaned up the `short_name_as_key()` functionality slightly.
> Make `NamedItemList` a list when it comes to type checking

- odxtools/cli/browse.py
- odxtools/cli/main.py
- tests/test_cli.py
This is a spin-off of #256: it adds a non-strict mode to all comand line tools whilst the patch that used to be in #256 only dealt with `list` and `compare`. using this mode is more robust regarding incorrect input files, bugs and unimplemented features in odxtools, but it might cause undefined behaviour.
> CLI: introduce a non-strict mode to all tools

- odxtools/templates/macros/printParentRef.xml.jinja2
- odxtools/write_pdx_file.py
this is supposed to be the short name of the container which contains the referenced layer, not the short name of the layer itself.
this might fix https://github.com/mercedes-benz/odxtools/issues/260. if it does, it is more generic than https://github.com/mercedes-benz/odxtools/pull/261 because with the approach suggested here, the parent of a layer does not necessarily need to be in the same container.
@willzhang05: can you check if the resulting files work with odxstudio for you?
> use the correct value for the DOCREF in PARENT-REFs

- odxtools/basicstructure.py
- odxtools/decodestate.py
- odxtools/endofpdufield.py
- odxtools/multiplexer.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/paramlengthinfotype.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
This is the first PR of a mini series to refactor the decoding code of odxtools. In this PR, we refactor the `DecodeState` class with the aim of not having to create copies during the decoding process:
- the attributes `cursor_position` and `origin_position` are introduced. The former points to the first undecoded byte whilst the latter points to the byte to which relative positions given by the BYTE-POSITION tag refer to.
- the `parameter_values` property is removed. Instead, the parameter values are kept as local variables in the respective decoding functions.
- `length_keys` and `table_keys` attributes are introduced, to keep track of inter-parameter dependencies
note that the "do not create copies" aim is not yet fully reached after this PR, but it will be at the end of this PR …
> Refactor decoding, part 1

- odxtools/basicstructure.py
- odxtools/cli/browse.py
- odxtools/cli/dummy_sub_parser.py
- odxtools/dataobjectproperty.py
- odxtools/decodestate.py
- odxtools/diagcodedtype.py
- odxtools/dtcdop.py
- odxtools/endofpdufield.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/multiplexer.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/paramlengthinfotype.py
- odxtools/standardlengthtype.py
- pyproject.toml
- tests/test_cli.py
- tests/test_diag_coded_types.py
The approach taken in this PR will serve as the template for all other objects which can be decoded (i.e., DOPs and parameters): decoding is done by a `decode_from_pdu()` method which takes a `DecodeState` object as their lone argument and returns the decoded physical value and the passed `DecodeState` is supposed to be changed so that it is set up to decode the next object after calling `decode_from_pdu()`.
IMO, this substantially reduces the mental load required to understand the decoding logic, because before this, parameters, diag coded types, and DOPs all used identical names for the decoding functions  but they behaved slightly different in terms of the parameters which they took and the types they returned...
Andreas Lauser &lt;andreas.lauser@mercedes-benz.com&gt;, on behalf of …
> Refactor decoding, part 2

- odxtools/cli/browse.py
- odxtools/decodestate.py
- odxtools/diagcodedtype.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/paramlengthinfotype.py
- odxtools/standardlengthtype.py
- tests/test_decoding.py
- tests/test_somersault.py
This PR is the final part of the decode code refactoring miniseries. It contains the "leftovers" which I've encountered and fixed while implementing the rest of the series and which require the API changes of the rest of the series to be present.
> Refactor decoding, part 4

- odxtools/basicstructure.py
- odxtools/diagservice.py
- odxtools/dynamiclengthfield.py
- odxtools/encodestate.py
- odxtools/endofpdufield.py
- odxtools/parameters/parameter.py
- odxtools/parameters/tablestructparameter.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
besides adding de- and encoding support for dynamic length fields, this PR also includes minor changes to the encoding infrastructure to bring it closer to how decoding now works and to make it more convenient. In particular the `_encode_into_blob()` method of `Parameter` was moved to `EncodeState` and renamed to `emplace_atomic_value()`  to make the API more analogous to `DecodeState.extract_atomic_value()`.
> DynamicLengthField: implement support for en- and decoding

- odxtools/diaglayer.py
- odxtools/diaglayertype.py
I recently noticed that the ODX specification for value inheritance slightly differed from the version which was implemented by odxtools:
- objects directly inherited from ECU-SHARED-DATA parents did not override objects inherited from diagnostic layers of different type
- the "not inherited" objects were not considered while populating the list, causing the function to produce undefined results if inheritance conflicts were solved using the NOT-INHERITED-* mechanism.
- inheritance conflicts where generally not handled explicitly.
This PR fixes these issues and we now hopefully fully adhere to the specification. (I doubt that it did matter for many datasets, though. For the ones I have access to, it didn't.)
Andreas Lauser &lt;andreas.lauser@mercedes-benz.com&gt;, on behalf of [MBition …
> fix the code computing value inheritance

- examples/somersaultecu.py
- odxtools/diagdatadictionaryspec.py
- odxtools/diaglayer.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_unit_spec.py
this is a spin-off of #274. It contains the janitorial changes to `DiagDataDictionarySpec` that originaly were contained of that PR. note that, in order to avoid conflicts, this PR also contains the patch which implements static fields. (reviewing this after #274 has been merged is thus probably advisable.)
> DiagDataDictionarySpec cleanup

- README.md
- odxtools/compumethods/compuscale.py
- odxtools/compumethods/createanycompumethod.py
- odxtools/compumethods/limit.py
- odxtools/dataobjectproperty.py
- odxtools/diaglayer.py
- odxtools/internalconstr.py
- odxtools/multiplexercase.py
- odxtools/scaleconstr.py
- odxtools/table.py
- odxtools/tablerow.py
This PR fixes the incompatible overrides of `from_et()` methods which require additional arguments by renaming them to `.{foo}_from_et()` (e.g. `Limit.limit_from_et()`). Some type checkers complain about this, IMO rightfully so.
Besides this, as a drive-by I've updated the `README` so that the snippets outlined there work with the latest odxtools version. (I don't think that this changelet merrits its own PR.)
> Avoid incompatible overrides

- odxtools/basicstructure.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/dynamicparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/systemparameter.py
- odxtools/parameters/tableentryparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- pyproject.toml
This is the base class of all parameters for which a position within the PDU can be defined. Interestingly, the XSD does not seem to feature *any* parameters that are not positionable, but let's reflect the class hierarchy implied by the ODX specification...
> Add `PositionableParam`

- odxtools/isotp_state_machine.py
- odxtools/parameters/reservedparameter.py
- odxtools/uds.py
This PR contains three small but important fixes for the decode code for bugs which recently slipped in.
> Smallish decode fixes

- odxtools/diaglayer.py
If I understood the spec correctly, this simply extends the pool of objects that are locally referenceable via ODXLINK (i.e., without having to explicitly specify the DOCREF attribute in the reference), and can thus be seen as a kind of "poor man's inheritance" mechanism.
> Implement the IMPORT-REF mechanism

- odxtools/multiplexer.py
- odxtools/parameterinfo.py
- tests/test_somersault.py
With this, the `parameter_info()` function handles more parameter types, deals with more DOP types and handles complex DOPs (structures) properly. Also, I tried to make the results more consistent, but IMO this is not too important, because the result of this function is intended to be informal and for human consumption.
Besides this I found a fixed a small mistake in the handling of case limits in the multiplexer code.
> Improve the free parameter info messages

- odxtools/basicstructure.py
- odxtools/multiplexercase.py
- odxtools/parameters/tablestructparameter.py
This requires to use a custom `_resolve_snrefs()` function because the parameter object itself cannot know the context from where it is called...
> TableStructParameter: allow the table key to be specified via SNREF

- odxtools/dataobjectproperty.py
- odxtools/diagcodedtype.py
- odxtools/dtcdop.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/paramlengthinfotype.py
- odxtools/standardlengthtype.py
- tests/test_diag_coded_types.py
- tests/test_encoding.py
This converts the diag coded types to the new and shiny encoding infrastructure. Note that doing this as a stand-alone change requires some kludges like creating temporary `EncodeState` objects. These will be removed by later PRs in the series...
> Refactor encoding, part 2 (diag coded types)

- odxtools/basicstructure.py
- odxtools/diagservice.py
- odxtools/dynamiclengthfield.py
- odxtools/encodestate.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/parameters/matchingrequestparameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/paramlengthinfotype.py
- odxtools/request.py
- odxtools/response.py
- odxtools/standardlengthtype.py
- odxtools/staticfield.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
this PR contains a few cleanups/improvements for the encoding machinery which have been made possible by the rest of the series.
> Refactor encoding, part 5 (the finale)

- odxtools/basicstructure.py
- odxtools/diagcomm.py
- odxtools/diaglayerraw.py
- odxtools/field.py
- odxtools/matchingparameter.py
- odxtools/multiplexercase.py
- odxtools/multiplexerdefaultcase.py
- odxtools/odxlink.py
- odxtools/parameters/codedconstparameter.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/nrcconstparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/physicalconstantparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/parameters/tablestructparameter.py
- odxtools/parameters/valueparameter.py
- odxtools/statechart.py
- odxtools/statetransition.py
- odxtools/tablerow.py
- odxtools/utils.py
- tests/test_decoding.py
- tests/test_encoding.py
This PR contains two SNREF related changes:
- We make it possible for any parameter to reference other parameters via short name reference. This can be regarded as a cleanup and should come with with a very limited practical impact. 
- Short name resolutions are no longer done by (mis)using `NamedItemList.get()`. This makes it possible to reference objects which do not exhibit short names that are valid python identifiers. (E.g. because they start with a digit.)
> Improve short name reference handling

- examples/mksomersaultmodifiedpdx.py
- examples/somersaultecu.py
- odxtools/cli/_print_utils.py
- odxtools/comparaminstance.py
- odxtools/compumethods/compuscale.py
- odxtools/description.py
- odxtools/diaglayer.py
- odxtools/element.py
- odxtools/relateddoc.py
- odxtools/scaleconstr.py
- odxtools/templates/comparam-spec.odx-c.xml.jinja2
- odxtools/templates/comparam-subset.odx-cs.xml.jinja2
- odxtools/templates/macros/printCompanyData.xml.jinja2
- odxtools/templates/macros/printComparamRef.xml.jinja2
- odxtools/templates/macros/printCompuMethod.xml.jinja2
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/templates/macros/printDescription.xml.jinja2
- odxtools/templates/macros/printElementId.xml.jinja2
- odxtools/templates/macros/printTable.xml.jinja2
- odxtools/utils.py
- tests/test_diag_coded_types.py
- tests/test_singleecujob.py
- tests/test_somersault.py
even though I never saw DESC tags containing anything other than a subset of HTML, the specification allows them to provide a list of URLs to auxiliary external documents and a text identifier (the TI attribute).
To make working with these objects as easy as possible and in order to simplify backwards compatibility, the `__str__()` method of these `Description` objects returns only the content of the tag.
> make descriptions conform to the specification

- odxtools/basicstructure.py
- odxtools/dynamicendmarkerfield.py
- odxtools/dynamiclengthfield.py
- odxtools/endofpdufield.py
- odxtools/multiplexer.py
- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/parameter.py
- odxtools/parameters/reservedparameter.py
- odxtools/parameters/tablekeyparameter.py
- odxtools/staticfield.py
- tests/test_decoding.py
The specification states that if the position of a parameter is not explicitly specified using BYTE-POSITION, "The parameter starts then at the byte edge next to the end of the last parameter". This PR changes the interpretation of "last parameter" from "parameter currently closest to the end of the PDU" to "most recently handled parameter". The reason is that IMO it is more likely that this is what is meant by the specification, and that it is slightly simpler to implement. That said, I consider it to be likely that no data set encountered in the wild is affected by this.
Besides this, a bug in dynamic endmarker fields is fixed by this PR: it turns out that the data occupied by the endmarker of these fields ought not to be considered consumed (why???), i.e., one needs to explicitly add a …
> Change interpretation of "last parameter"

- odxtools/database.py
- odxtools/diaglayer.py
- odxtools/diaglayercontainer.py
- odxtools/parentref.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_ecu_variant_matching.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
this is a spin-off of #310: We provide a backlink from the diagnostic layer to the database which contains the layer in question (this is necessary to access the contents of auxiliary files from objects contained by the diag layer). Note that this seemingly trivial change is surprisingly difficult to implement, as it requires some custom `__deepcopy__()` methods, or else the whole database would be copied if some relatively trivial objects like `ParentRef` are copied...
> DiagLayer: remember the database

- odxtools/exceptions.py
- odxtools/parameters/reservedparameter.py
`encode_state.emplace_bytes()` only works if the bit position is zero. Besides this, #315 is also included because @radoering does not seem to be able to sign the CLA.
> Fix reserved encoding

- odxtools/basicstructure.py
- odxtools/diagservice.py
- odxtools/exceptions.py
- odxtools/parameters/nrcconstparameter.py
- tests/test_decoding.py
- tests/test_encoding.py
if a negative response contains an NRC-CONST parameter, where the parameter's value is not in the list of expected values, the response is not applicable and decoding should be stopped at this point. (Thus, NRC-CONST parameters are a multiplexer mechanism which filters responses based on the value of some other parameter.)
This patch implements this by introducing a new `DecodeMismatch` exception which is raised whenever a NRC-CONST parameter which exhibits an unexpected value is encountered. The higher-level routines for decoding responses then ignore these exceptions when appropriate. IMO, this solution is a bit sub-optimal because it uses exceptions for flow control in normal operation, but alternative implementations would be far more complex.
Andreas Lauser …
> Properly support decoding NRC-CONST parameters

- .github/workflows/tests.yml
- odxtools/odxtypes.py
- tests/test_odxtypes.py
the latest version of `ruff` must be called using `ruff check <path>` instead of via `ruff <path>`.
> make the continuous integration work again

- odxtools/diaglayer.py
- odxtools/dtcdop.py
- odxtools/odxlink.py
Since #318 became quite a bit too off topic, I figured it was a good idea to spin off all changes not directly related to multiplexer coding, so this PR contains:
- `DiagLayer.decode()` now re-raises encountered `DecodeError`s if the binary data is also not decodable as a global negative response. The old behavior accidentally was to never raise  `DecodeError`.
- a `DecodeError` exception is raised if unknown DTC numbers are passed to DtcDop parameters.
- the ODXLINK reference machinery is fixed for the case where multiple document fragments provided objects featuring the same local ID
- The `._database` object of diagnostic layers is removed again. (this became unnecessary because of SNREF context objects...)
Andreas Lauser &lt;andreas.lauser@mercedes-benz.com&gt;, on behalf of [MBition …
> Some miscellaneous fixes

- examples/somersaultecu.py
- odxtools/commrelation.py
- odxtools/diaglayerraw.py
- odxtools/diagvariable.py
- odxtools/dyndefinedspec.py
- odxtools/swvariable.py
- odxtools/templates/macros/printDiagVariable.xml.jinja2
- odxtools/templates/macros/printDynDefinedSpec.xml.jinja2
- odxtools/templates/macros/printVariant.xml.jinja2
- odxtools/variablegroup.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_ecu_variant_matching.py
- tests/test_encoding.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
In true "design by committee" spirit, the ODX specification supports to layer an entirely different communication paradigm over its default RPC-based model: Diagnostic variables. In this model, communication with the ECU is done by reading from and writing to a set of "variables". ODX glues this communication approach on its "normal" service-oriented model by specifying a set of variables plus setter and getter services for each.
Note that, since odxtools is not concerned with communicating with ECUs directly, odxtools can only expose the required information for this, not implement this approach itself.
Besides the diagnostic variables infrastructure, this patch also adds the code to internalize the information necessary for dynamically defined messages (`DYN-DEFINED-SPEC`), i.e., …
> Implement diagnostic variables

- odxtools/parameters/tablekeyparameter.py
unfortunately, the `Table` and `TableRow` classes are only available during type checking (i.e., not during normal execution) because this would lead to circular imports.
this should fix https://github.com/mercedes-benz/odxtools/issues/324.
> tablekeyparameter: fix short name reference resolution

- odxtools/specialdatagroup.py
This prevents these SDG captions to be added multiple times (i.e., for SDGs which only reference the caption but do not define it). Under normal circumstances, this only results in slightly lower performance, but in special situations like having to modify a database, it can lead to SDG captions added which are defined nowhere. (I recently stumbled over such a case.)
> SDGs: if the SDG caption is referenced, do not add its IDs to the odxlink database

- odxtools/environmentdatadescription.py
Just like for https://github.com/mercedes-benz/odxtools/pull/328, under normal circumstances, this only results in slightly lower performance, but in special situations like having to modify a database based on another, it can lead to environment data objects being falsely added. (I recently stumbled over such a case.)
> EnvironmentDataDescription: do not add links to referenced environment data objects

- odxtools/parameterinfo.py
- odxtools/templates/macros/printCompuMethod.xml.jinja2
This PR contains a fix for the output writing code (the values of limits might be strings with special characters and must thus be escaped) and for the function which summarizes the expected parameters of codec objects (we don't want to see the representation of `CodedConst` objects there).
> Random fixes

- odxtools/dynamicendmarkerfield.py
ODX version 2.0 uses DATA-OBJECT-PROP-REF tag instead of DYN-END-DOP-REF tag.
> odx 2.0 does not use DYN-END-DOP-REF tag

- odxtools/odxtypes.py
The current implementation of **odxtypes.parse_int** function only supports the conversion of base 10 values into integers, not hex or other bases.
> odxtypes.parse_int: detect the value base automatically

- odxtools/multiplexer.py
An EncodeError occurs, showing that the multiplexer does not know the current case when it is the default case.
> multiplexer.encode_into_pdu: Fix when case_spec is a string and it is the default case

- odxtools/database.py
Remove unused parameters from constructor and enable adding PDX files based on an IO / file-like object to a database.
Michael Hahn <[michael.a.hahn@mercedes-benz.com](mailto:michael.a.hahn@mercedes-benz.com)>, on behalf of [MBition GmbH](https://mbition.io/).
> Enable loading PDX from IO

- odxtools/environmentdatadescription.py
- odxtools/multiplexer.py
- odxtools/multiplexercase.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
These objects are `NamedElements` anyway and accessing the items of these lists via their name is much more convenient...
> make `Multiplexer.cases` and `EnvironmentDataDescription.env_datas` `NamedItemLists`

- odxtools/diaglayers/basevariantraw.py
- odxtools/diaglayers/ecushareddataraw.py
- odxtools/diaglayers/ecuvariantraw.py
- odxtools/diaglayers/functionalgroupraw.py
- odxtools/diaglayers/hierarchyelementraw.py
- odxtools/diaglayers/protocolraw.py
Since diagnostic layers constitute document fragments in addition to the containers which contain them, the odxlink ids must reflect that. So far, this did not happen for objects which are added by one of the concrete diagnostic layers classes, i.e. objects which were not handled by the diagnostic layer base class.
> Fix the document fragments for objects not featured by the base diag layer

- .gitignore
- odxtools/compumethods/compucodecompumethod.py
- odxtools/compumethods/compuinternaltophys.py
- odxtools/compumethods/compumethod.py
- odxtools/compumethods/compuphystointernal.py
- odxtools/compumethods/createanycompumethod.py
- odxtools/compumethods/linearcompumethod.py
- odxtools/compumethods/ratfunccompumethod.py
- odxtools/compumethods/ratfuncsegment.py
- odxtools/compumethods/scaleratfunccompumethod.py
- odxtools/dataobjectproperty.py
- odxtools/dtcdop.py
- tests/test_compu_methods.py
This PR implements the compu methods specified by the ODX standard which have so far been MIA in `odxtools`. These are `COMPUCODE`, `RAT-FUNC` and `SCALE-RAT-FUNC`.
> Implement remaining compumethods

- odxtools/parameters/systemparameter.py
- tests/test_encoding.py
If the value of these parameters are not explicitly specified, their value is determined by looking at the current state of the system the program is running on. (If their type is one of the values specified by the ODX standard.)
> Implement en- and decoding of SYSTEM parameters

- examples/somersaultecu.py
- odxtools/audience.py
- odxtools/unitspec.py
- tests/test_unit_spec.py
This fixes two small inconveniences which I've recently stumbled over.
> Fix papercuts

- odxtools/compumethods/compucodecompumethod.py
- odxtools/odxtypes.py
- odxtools/parameterinfo.py
It now knows about system parameters, `SCALE-LINEAR`, `RAT-FUNC` and `SCALE-RAT-FUNC` and `COMPU-CODE` parameters. Also, the code is a bit easier to read and contains a few smaller drive-by fixes.
this is a spin-off of #347 and thus build on top of that PR.
> Improve the `parameter_info()` function

- examples/somersaultecu.py
- odxtools/diaglayers/diaglayer.py
- odxtools/diaglayers/diaglayerraw.py
- odxtools/diagservice.py
- odxtools/library.py
- odxtools/templates/macros/printCompuMethod.xml.jinja2
- odxtools/templates/macros/printDiagLayer.xml.jinja2
- odxtools/templates/macros/printLibrary.xml.jinja2
- odxtools/templates/macros/printSingleEcuJob.xml.jinja2
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_ecu_variant_matching.py
- tests/test_encoding.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
AFAICS, these are pretty much equivalent to `PROG-CODE`.
Besides implementing libraries, this patch also fixes a few minor but important issues with the `PROG-CODE` handling.
(Note that ODX likes to pluralize everything by appending a `s` to the singular, so we get gems like `LIBRARYS` or `FUNCTIONAL-CLASSS` in the standard.)
> implement libraries

- odxtools/minmaxlengthtype.py
Add `bytearray` in condition to verify the data type of `MinMaxLengthType` when `encode_into_pdu` parameter's value. #351
> fix MinMaxLengthType error when encoding bytearray value

- odxtools/dtcdop.py
- odxtools/dyndefinedspec.py
due to some copy-and-pasto, `DynDefinedSpec._build_odxlinks()` unconditionally called itself and the `oid` parameter was missing from the fallback code for DTC decoding. (Be aware that the latter points towards an incomplete dataset.)
> attempt to fix issue #354 and #355

- odxtools/diaglayers/diaglayer.py
- odxtools/odxlink.py
This merge request introduces an "overwrite" parameter to the update method of the OdxLinkDatabase class. This parameter, set to False for imported references, allows local references to take priority over imported ones.
In diaglayer. _resolve_odxlinks, the overwrite=False setting ensures that imported references do not override locally defined references. 
odxtools version: 8.0.5
> Priority should be given to local refs

- odxtools/cli/_print_utils.py
- odxtools/cli/browse.py
Issue resolved: I have updated the list bash output by replacing the tabulate table with rich tables. 
File updated: cli/_print_utils.py
The output looks like this:
> change list command output from tabulate to rich tables

- odxtools/cli/_print_utils.py
- odxtools/cli/compare.py
- odxtools/cli/list.py
- pyproject.toml
this is a minor follow-up to https://github.com/mercedes-benz/odxtools/pull/359: table columns are now always of type `List[str]`, better variable names for the column lists (´*_column´) and removal of the now unused `tabulate` dependency...
> print_utils: minor cleanups

- odxtools/parameterinfo.py
the code for handling the upper limit was indented one level too deep which caused exceptions for `free_parameters_info()`.
> fix the `*segment_info()` functions

- odxtools/comparamspec.py
- odxtools/comparamsubset.py
- odxtools/database.py
- odxtools/diaglayercontainer.py
- odxtools/odxcategory.py
- odxtools/templates/comparam-spec.odx-c.xml.jinja2
- odxtools/templates/comparam-subset.odx-cs.xml.jinja2
- odxtools/templates/diag_layer_container.odx-d.xml.jinja2
- odxtools/templates/macros/printOdxCategory.xml.jinja2
The spec defines `OdxCategory` as the base for any top-level content tag in an ODX XML file. odxtools currently implements `DIAG-LAYER-CONTAINER`, `COMPARAM-SPEC` and `COMPARAM-SUBSET` (all of them are relevant for diagnostics based on UDS). Currently missing are the categories `ECU-CONFIG` (variant coding), `FLASH` (firmware blobs for flashing), `FUNCTION-DICTIONARY` (functionality distributed over multiple ECUs) and `MULTIPLE-ECU-JOB-SPEC` (multiple-ecu jobs).
> Introduce `OdxCategory`

- odxtools/parameters/lengthkeyparameter.py
- odxtools/parameters/tablekeyparameter.py
this fixes https://github.com/mercedes-benz/odxtools/issues/375 and the non-snref related part of https://github.com/mercedes-benz/odxtools/pull/373 .
> Fix issue #375 and PR #373

- odxtools/nameditemlist.py
- odxtools/tablerow.py
- tests/test_decoding.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_odxtools.py
I am working on caching the PDX config parsing result to avoid reparsing it each time, using Pickle for serialization.
During the pickling process, no issues were encountered. However, during the unpickling step, the following exception occurred: "maximum recursion depth exceeded" which originated in the NamedItemList class.
The recursion occurred due to infinite calls to the NamedItemList.\_\_getattr__ method. Specifically, the code attempted to access a property that was uninitialized at the time, causing the \_\_getattr__ to be invoked repeatedly during the reconstruction of the object.
To address this, I added the \_\_reduce__ method which explicitly defines how an object is serialized and reconstructed during pickling and unpickling. After adding this method, the recursion issue was …
> Add Pickle support

- odxtools/environmentdatadescription.py
it turns out that the specification only mandates that the base data type of the DOP used by the referenced parameter must be A_UINT32, but the DOP does not need to be a DTC-DOP.
> fix en- and decoding of environment data descriptions

- odxtools/standardlengthtype.py
- tests/test_encoding.py
IMO this is a somewhat exotic feature, but since it is in the spec there probably is somebody out there who uses it...
> implement support for condensed bit masks

- examples/somersaultecu.py
- odxtools/physicaltype.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
IMO, using positional parameters for dataclasses is usually bad style and it would break as soon as we switch the minimum python version to 3.10 and make these classes `kw_only`...
> `PhysicalDataType`: always pass all parameters by name

- examples/somersaultecu.py
- odxtools/comparamspec.py
- odxtools/comparamsubset.py
- odxtools/diaglayercontainer.py
- odxtools/diaglayers/diaglayerraw.py
- odxtools/minmaxlengthtype.py
- odxtools/odxcategory.py
- odxtools/odxlink.py
- odxtools/parameters/tableentryparameter.py
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/templates/macros/printProtocol.xml.jinja2
- tests/test_compu_methods.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_ecu_variant_matching.py
- tests/test_ecu_variant_patterns.py
- tests/test_encoding.py
- tests/test_readparameters.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
This replaces most cases where strings are used by odxtools but the specification limits the possible values with `Enum` classes. The main benefit is that using enumeration classes are checked at runtime and can also be type checked using e.g. `mypy`.
> More enums

- odxtools/dataobjectproperty.py
This merge request adds support for returning the default value when the internal value is invalid. If the internal value is not defined, the method will check for a defined default value and return it; otherwise, it will raise an exception.
odxtools version: 9.2.0
> DataObjectProperty.decode_from_pdu: support returning the default value when the internal value is invalid

- odxtools/dataobjectproperty.py
Fix for https://github.com/mercedes-benz/odxtools/pull/389
I initially used `str(default_value)`, but I didn't access its 'value' attribute. It should be `str(default_value.value)` .
> Small fix 

- odxtools/dataobjectproperty.py
- odxtools/encodestate.py
- odxtools/matchingparameter.py
- odxtools/minmaxlengthtype.py
- odxtools/odxtypes.py
- odxtools/standardlengthtype.py
- odxtools/utils.py
The `SupportsBytes` protocol only recognizes types that explicitly implement `__bytes__()`.
Python 3.12 implements `__bytes__()`, but Python 3.9 does not.
This change affects the behavior of `isinstance(obj, SupportsBytes)`, which previously returned `False` for bytes in Python 3.9 but now returns `True` in Python 3.12.
**### Impact `on standardlengthtype.__unapply_mask`:**
This change has impacted the behavior of the `standardlengthtype.__unapply_mask(self, raw_value: AtomicOdxType)` method.
- When `raw_value` is of type bytes, Python 3.9 raises an odxraise and returns raw_value as-is (in bytes) in non-strict mode.
- In Python 3.12, the condition at [this line](https://github.com/mercedes-benz/odxtools/blob/5cc2c95ab238d482fc1ffc3819d45814f007871d/odxtools/standardlengthtype.py#L173) …
> Fix SupportsBytes Behavior Change in Python 3.12

- .github/workflows/tests.yml
- odxtools/dataobjectproperty.py
- odxtools/encodestate.py
- odxtools/matchingparameter.py
- odxtools/minmaxlengthtype.py
- odxtools/odxtypes.py
- odxtools/parameters/tablestructparameter.py
- odxtools/standardlengthtype.py
- odxtools/utils.py
This PR moves the `BytesTypes` alias from `utils.py` to `odxtypes.py` and adds a `.table` property to `TableStructParameter`s. (Both patches are drive-by fixes for a more substantial change I am currently working on.)
> Small fixes

- odxtools/diagnostictroublecode.py
- odxtools/templates/macros/printDOP.xml.jinja2
- odxtools/text.py
- tests/test_decoding.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
This is a tag containing an ordinary string but the tag itself has an additional `TI` (text identifier) attribute. The only user is the `DTC` tag and it also seems to be very unusual to specify a text identifier there.
This is the last missing tag type that can be specified inside `DIAG-LAYER-CONTAINER`, `COMPARAM-SUBSET` or `COMPARAM-SPEC`, i.e., after this commit the diagnostics related functionality of the ODX standard should be fully covered by odxtools... (modulo bugs)
> implement the TEXT tag

- odxtools/diagservice.py
According to the specification, the bit mask property for `PosResponseSuppressible` is defined using the tag name **BIT-MASK**, not **BITMASK**.
odxtools version: 9.5.0
> Fix tag name for PosResponseSuppressible.bit_mask

- odxtools/posresponsesuppressible.py
- odxtools/standardlengthtype.py
- odxtools/templates/macros/printService.xml.jinja2
- odxtools/utils.py
This is a follow-up of https://github.com/mercedes-benz/odxtools/pull/402 proposed by @kayoub5. Besides eliminating a few lines of copy-and-pasted code, a surprising number of things can go wrong here, so it makes sense to centralize this.
> centralize parsing of `xsd:hexBinary` values

- odxtools/cli/_print_utils.py
- odxtools/cli/browse.py
- odxtools/cli/list.py
- odxtools/comparaminstance.py
- odxtools/compositecodec.py
- odxtools/compumethods/linearsegment.py
- odxtools/compumethods/ratfuncsegment.py
- odxtools/compumethods/scalelinearcompumethod.py
- odxtools/compumethods/tabintpcompumethod.py
- odxtools/dataobjectproperty.py
- odxtools/environmentdatadescription.py
- odxtools/leadinglengthinfotype.py
- odxtools/minmaxlengthtype.py
- odxtools/nameditemlist.py
- odxtools/odxtypes.py
- odxtools/parameters/parameterwithdop.py
- odxtools/parameters/tablestructparameter.py
- odxtools/statemachine.py
- odxtools/statetransitionref.py
- odxtools/tablerow.py
- pyproject.toml
This check mandates to pass a union type to `isinstance()` and is [deprecated](https://docs.astral.sh/ruff/rules/non-pep604-isinstance/). This PR is basically a spin-off of #405. All good things about this patch are @zariiii9003's, whilst all bugs are mine.
> ruff: disable deprecated UP038 check

- odxtools/multiplexer.py
- tests/test_diag_data_dictionary_spec.py
This MR introduces support for calculating the static length of the multiplexer when all cases have the same size, enabling the codec length to be considered static.
> support computing the MUX static length if all the cases have the same size

- examples/somersaultecu.py
- odxtools/comparamspec.py
- odxtools/comparamsubset.py
- odxtools/database.py
- odxtools/diaglayercontainer.py
- odxtools/diaglayers/diaglayerraw.py
- odxtools/diaglayers/hierarchyelement.py
- odxtools/odxcategory.py
- odxtools/odxdoccontext.py
- odxtools/odxlink.py
- odxtools/templates/macros/printParentRef.xml.jinja2
- odxtools/writepdxfile.py
- tests/test_compu_methods.py
- tests/test_decoding.py
- tests/test_diag_coded_types.py
- tests/test_diag_data_dictionary_spec.py
- tests/test_encoding.py
- tests/test_readparameters.py
- tests/test_singleecujob.py
- tests/test_unit_spec.py
- tests/test_variant_matching.py
- tests/test_variant_patterns.py
As suggested in #405.
I tried converting OdxLinkRef into a frozen dataclass, but subclasses assign attributes after instantiation.
> Convert OdxLinkId.doc_fragments and OdxLinkRef.ref_docs to tuple

- odxtools/database.py
- odxtools/diaglayers/diaglayer.py
- odxtools/multipleecujob.py
- odxtools/multipleecujobspec.py
- odxtools/outputparam.py
- odxtools/snrefcontext.py
- odxtools/templates/macros/printAdminData.xml.jinja2
- odxtools/templates/macros/printDiagDataDictionarySpec.xml.jinja2
- odxtools/templates/macros/printDiagLayer.xml.jinja2
- odxtools/templates/macros/printElementId.xml.jinja2
- odxtools/templates/macros/printFunctionalClass.xml.jinja2
- odxtools/templates/macros/printMultipleEcuJob.xml.jinja2
- odxtools/templates/multiple-ecu-job-spec.odx-m.xml.jinja2
- odxtools/writepdxfile.py
- tests/test_multiple_ecu_jobs.py
This ODX category is used to describe programs that are run on the diagnostic tester and which involve calling services of multiple ECUs. (Single ECU jobs are contained by their respective ECU as diagnostic communication objects.)
Andreas Lauser <[andreas.lauser@mercedes-benz.com](mailto:andreas.lauser@mercedes-benz.com)>, on behalf of [MBition GmbH](https://mbitionio/).
> Implement multiple-ECU jobs
